//! Blobs: large binaries that travel by reference (`$blob`) instead of
//! inline in the JSON context. [`BlobStore`] is the per-execution storage;
//! [`BlobStoreFactory`] the injection point.

use std::path::{Path, PathBuf};

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::error::{WorkflowError, codes};

/// Reference to a large binary/file under the spec's `$blob` convention:
/// blobs do not travel inline in the JSON context, they travel by reference.
///
/// ```json
/// { "$blob": "01J…", "name": "ventas.csv.gz", "size": 52428800 }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BlobRef {
    /// Unique identifier of the blob within the execution
    #[serde(rename = "$blob")]
    pub id: String,
    /// Suggested file name
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Size in bytes
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<u64>,
}

impl BlobRef {
    /// Interprets a JSON value as a blob reference, if it has the right shape
    pub fn from_value(value: &serde_json::Value) -> Option<Self> {
        serde_json::from_value(value.clone()).ok()
    }
}

/// Blob storage with lifecycle tied to an execution.
/// Extensions read/write blobs through the context; they never touch
/// the filesystem on their own.
#[async_trait]
pub trait BlobStore: Send + Sync + 'static {
    /// Stores bytes as a new blob
    async fn put(&self, data: Vec<u8>, name: Option<String>) -> Result<BlobRef, WorkflowError>;

    /// Reads the full content of a blob
    async fn get(&self, blob: &BlobRef) -> Result<Vec<u8>, WorkflowError>;

    /// Imports an existing file by copying it into the store (for producers
    /// that write to disk via streaming before registering the blob)
    async fn import_file(
        &self,
        path: &Path,
        name: Option<String>,
    ) -> Result<BlobRef, WorkflowError>;

    /// Local path of the blob, for consumers that read via streaming.
    /// In v1 all blobs are file-backed.
    fn local_path(&self, blob: &BlobRef) -> Result<PathBuf, WorkflowError>;

    /// Deletes all blobs from the execution
    async fn cleanup(&self) -> Result<(), WorkflowError>;
}

/// [`BlobStore`] factory: the storage injection point.
///
/// The store has a per-execution lifecycle (created with the
/// `execution_id` and cleaned up when the root execution ends), which is why
/// the injectable is the factory and not an instance. Configured via
/// `WorkflowExecutorBuilder::blobs`; the default is [`TempDirBlobFactory`].
pub trait BlobStoreFactory: Send + Sync {
    /// Creates the store for a new execution.
    fn create(&self, execution_id: &str) -> std::sync::Arc<dyn BlobStore>;
}

/// Default factory: one [`TempDirBlobStore`] per execution.
#[derive(Debug, Clone, Copy, Default)]
pub struct TempDirBlobFactory;

impl BlobStoreFactory for TempDirBlobFactory {
    fn create(&self, execution_id: &str) -> std::sync::Arc<dyn BlobStore> {
        std::sync::Arc::new(TempDirBlobStore::new(execution_id))
    }
}

/// `BlobStore` v1: a temporary directory per execution, deleted when
/// the workflow ends (and as a safety net, on drop).
pub struct TempDirBlobStore {
    dir: PathBuf,
}

impl TempDirBlobStore {
    /// Creates the store for an execution. The directory is lazily
    /// created on the first `put`/`import_file`.
    pub fn new(execution_id: &str) -> Self {
        Self {
            dir: std::env::temp_dir().join(format!("workflow-forge-{execution_id}")),
        }
    }

    /// Root directory of this execution's blobs
    pub fn dir(&self) -> &Path {
        &self.dir
    }

    async fn ensure_dir(&self) -> Result<(), WorkflowError> {
        tokio::fs::create_dir_all(&self.dir)
            .await
            .map_err(|e| io_error("could not create blob directory", e))
    }

    fn blob_path(&self, id: &str) -> Result<PathBuf, WorkflowError> {
        // Ids are UUIDs generated by the store; anything else is
        // a forged reference (e.g., path traversal)
        if id.is_empty() || !id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-') {
            return Err(WorkflowError::new(
                codes::INVALID_BLOB_ID,
                format!("Blob id '{id}' is not valid"),
            ));
        }
        Ok(self.dir.join(id))
    }
}

#[async_trait]
impl BlobStore for TempDirBlobStore {
    async fn put(&self, data: Vec<u8>, name: Option<String>) -> Result<BlobRef, WorkflowError> {
        self.ensure_dir().await?;
        let id = uuid::Uuid::now_v7().to_string();
        let size = data.len() as u64;
        let path = self.dir.join(&id);
        tokio::fs::write(&path, data)
            .await
            .map_err(|e| io_error("could not write blob", e))?;
        Ok(BlobRef {
            id,
            name,
            size: Some(size),
        })
    }

    async fn get(&self, blob: &BlobRef) -> Result<Vec<u8>, WorkflowError> {
        let path = self.blob_path(&blob.id)?;
        tokio::fs::read(&path).await.map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                blob_not_found(&blob.id)
            } else {
                io_error("could not read blob", e)
            }
        })
    }

    async fn import_file(
        &self,
        path: &Path,
        name: Option<String>,
    ) -> Result<BlobRef, WorkflowError> {
        self.ensure_dir().await?;
        let id = uuid::Uuid::now_v7().to_string();
        let dest = self.dir.join(&id);
        let size = tokio::fs::copy(path, &dest)
            .await
            .map_err(|e| io_error("could not import file into store", e))?;
        let name = name.or_else(|| path.file_name().map(|n| n.to_string_lossy().into_owned()));
        Ok(BlobRef {
            id,
            name,
            size: Some(size),
        })
    }

    fn local_path(&self, blob: &BlobRef) -> Result<PathBuf, WorkflowError> {
        let path = self.blob_path(&blob.id)?;
        if !path.exists() {
            return Err(blob_not_found(&blob.id));
        }
        Ok(path)
    }

    async fn cleanup(&self) -> Result<(), WorkflowError> {
        match tokio::fs::remove_dir_all(&self.dir).await {
            Ok(()) => Ok(()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(io_error("could not clean up blob directory", e)),
        }
    }
}

// Safety net: if the execution ends without cleanup (e.g., panic),
// the temporary directory is not left orphaned
impl Drop for TempDirBlobStore {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.dir);
    }
}

fn io_error(message: &str, source: std::io::Error) -> WorkflowError {
    let mut err = WorkflowError::new(codes::BLOB_IO_ERROR, format!("{message}: {source}"));
    err.source = Some(Box::new(source));
    err
}

fn blob_not_found(id: &str) -> WorkflowError {
    WorkflowError::new(
        codes::BLOB_NOT_FOUND,
        format!("Blob '{id}' does not exist in this execution"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn store() -> TempDirBlobStore {
        TempDirBlobStore::new(&uuid::Uuid::now_v7().to_string())
    }

    #[tokio::test]
    async fn put_get_roundtrip_y_serde() {
        let store = store();
        let blob = store
            .put(b"hola blob".to_vec(), Some("saludo.txt".into()))
            .await
            .unwrap();

        assert_eq!(blob.name.as_deref(), Some("saludo.txt"));
        assert_eq!(blob.size, Some(9));

        // The reference serializes with the spec shape
        let as_json = serde_json::to_value(&blob).unwrap();
        assert_eq!(as_json["$blob"], json!(blob.id));
        assert_eq!(BlobRef::from_value(&as_json), Some(blob.clone()));

        assert_eq!(store.get(&blob).await.unwrap(), b"hola blob");
        store.cleanup().await.unwrap();
    }

    #[tokio::test]
    async fn import_file_y_local_path() {
        let store = store();
        let origen = std::env::temp_dir().join(format!("wf-test-{}", uuid::Uuid::now_v7()));
        tokio::fs::write(&origen, b"contenido").await.unwrap();

        let blob = store.import_file(&origen, None).await.unwrap();
        assert_eq!(blob.size, Some(9));
        assert!(blob.name.as_deref().unwrap().starts_with("wf-test-"));

        let path = store.local_path(&blob).unwrap();
        assert_eq!(std::fs::read(path).unwrap(), b"contenido");

        tokio::fs::remove_file(&origen).await.unwrap();
        store.cleanup().await.unwrap();
    }

    #[tokio::test]
    async fn ids_forjados_son_rechazados() {
        let store = store();
        store.put(b"x".to_vec(), None).await.unwrap();

        let forjado = BlobRef {
            id: "../../../etc/passwd".into(),
            name: None,
            size: None,
        };
        assert_eq!(
            store.get(&forjado).await.unwrap_err().code,
            "INVALID_BLOB_ID"
        );
        assert_eq!(
            store.local_path(&forjado).unwrap_err().code,
            "INVALID_BLOB_ID"
        );

        let inexistente = BlobRef {
            id: uuid::Uuid::now_v7().to_string(),
            name: None,
            size: None,
        };
        assert_eq!(
            store.get(&inexistente).await.unwrap_err().code,
            "BLOB_NOT_FOUND"
        );
        store.cleanup().await.unwrap();
    }

    #[tokio::test]
    async fn cleanup_elimina_el_directorio() {
        let store = store();
        store.put(b"x".to_vec(), None).await.unwrap();
        let dir = store.dir().to_path_buf();
        assert!(dir.exists());

        store.cleanup().await.unwrap();
        assert!(!dir.exists());
        // idempotent
        store.cleanup().await.unwrap();
    }
}
